import permissions from './permissions';

export default {
    Administrador: permissions.map((permission) => permission.name),
    Gerente: [
        'CreateUser',
        'ReadUser',
        'UpdateUser',
        'DeleteUser',
        'CreateContact',
        'ReadContact',
        'UpdateContact',
        'DeleteContact',
        'ReadPlace',
        'UpdatePlace',
        'CreateCategory',
        'ReadCategory',
        'UpdateCategory',
        'DeleteCategory',
        'CreateProduct',
        'ReadProduct',
        'UpdateProduct',
        'DeleteProduct',
        'CreatePrice',
        'ReadPrice',
        'UpdatePrice',
        'DeletePrice',
        'CreateMenu',
        'ReadMenu',
        'UpdateMenu',
        'DeleteMenu',
        'CreateImage',
        'ReadImage',
        'UpdateImage',
        'DeleteImage',
    ],
    Atendente: [
        'ReadOrganizationRole',
        'ReadUser',
        'ReadContact',
        'UpdateContact',
        'ReadPlace',
        'ReadCategory',
        'ReadProduct',
        'ReadPrice',
        'ReadMenu',
        'ReadImage',
    ],
    Cliente: [
        'ReadOrganizationRole',
        'ReadUser',
        'ReadContact',
        'UpdateContact',
        'ReadPlace',
        'ReadCategory',
        'ReadProduct',
        'ReadPrice',
        'ReadMenu',
        'ReadImage',
    ],
    Entregador: [
        'ReadOrganizationRole',
        'ReadUser',
        'ReadContact',
        'UpdateContact',
        'ReadPlace',
        'ReadCategory',
        'ReadProduct',
        'ReadPrice',
        'ReadMenu',
        'ReadImage',
    ],
};
